### ISSUE TITLE
Switch from klog to zap for logging

### ISSUE THREAD

**Issue by SEJeff** [asymmetric-research/solana_exporter#27]
Uber has a [structured logging library named zap](https://github.com/uber-go/zap) that is designed for high performance structured logging. The [klog](https://pkg.go.dev/k8s.io/klog) library makes more sense for a larger project like kubernetes and follows the google style logging a bit more.

## Checklist

- [ ] Sensible log setup code
- [ ] Replacing klog with zap

**Comment by Dev79844** [comment]
Hello @SEJeff!
I would like to work on this issue.

**Comment by SEJeff** [comment]
Hey @Dev79844 we were hoping to get to this feature in the next few months. If you would like to work on it before then that is great. I would suggest you do a few things first:

* Fix your git client to have your actual name and email. Commits like [this](https://github.com/Dev79844/scalable-chat-go/commit/0522a7a7a3a6a929ece8ad03f9055053f5c9e8ab.patch) where your author info is `Dev Parikh <51128342+Dev79844@users.noreply.github.com>` are not reasonable
* Enable gpg signing and [sign your commits](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits)

Do you run solana nodes that you want to monitor?

**Comment by Dev79844** [comment]
Hey @SEJeff!
Sorry for the late reply. I will do the following things and I would like to work on this issue. 
I don't run any solana nodes.
