### ISSUE TITLE
Dockerfile is broken

### ISSUE THREAD

**Issue by BSC-aujl** [asymmetric-research/solana_exporter#38]
Building a Docker image from the repo is not working

The error hints that we need to get a repo

```
------                                                                                                                             
 > [builder 4/4] RUN CGO_ENABLED=0 go build -o /opt/bin/app github.com/certusone/solana_exporter/cmd/solana_exporter:              
0.241 no required module provides package github.com/certusone/solana_exporter/cmd/solana_exporter; to add it:
0.241 	go get github.com/certusone/solana_exporter/cmd/solana_exporter
```

Adding 

`RUN go get github.com/certusone/solana_exporter/cmd/solana_exporter`

before the line

`RUN CGO_ENABLED=0 go build -o /opt/bin/app github.com/certusone/solana_exporter/cmd/solana_exporter`

fixes the build for me

**Comment by SEJeff** [comment]
The path is wrong since it was migrated from the certusone github org. I've fixed this in #42. Thanks for the report.
