### ISSUE TITLE
Add identity label to all metrics

### ISSUE THREAD

**Issue by johnstonematt** [asymmetric-research/solana_exporter#56]
The identity label introduced in #55  (represents the identity of the node from which the metric was fetched) should be added to all metrics.

**Comment by johnstonematt** [comment]
Upon further research, [the docs](https://prometheus.io/docs/instrumenting/writing_exporters/#target-labels-not-static-scraped-labels) actually say this is a bad idea, for reasons that make sense.

Particularly:

> The second case is when a label is really a target label. These are things like region, cluster names, and so on, that come from your infrastructure setup rather than the application itself. It’s not for an application to say where it fits in your label taxonomy, that’s for the person running the Prometheus server to configure and different people monitoring the same application may give it different names.

I think it makes a pretty good point for removing the `identity` label and leaving it up to the user.

**Comment by johnstonematt** [comment]
Haven't gotten much response here, so I am going to go ahead and close this issue in favour of removing the identity label from all metrics. @GranderStark @SEJeff feel free to voice any disagreements. Closing this in favour of #63

**Comment by GranderStark** [comment]
I'm not oppose to removing identity, but reason `These are things like region, cluster names, and so on, that come from your infrastructure setup rather than the application itself` not fits here - identity label reflects information about the application instance rather than external infrastructure.

**Comment by johnstonematt** [comment]
Personally I think it still fits in that category. As you say, the identity label reflects information about the application instance, it's directly determined by whoever configures the `rpcUrl`. If I were running multiple nodes, I might want to organise the metrics by some other internal/personalised system for keeping track of things.
