### ISSUE TITLE
Use getBlockProduction instead of calculating skip rate ourselves

### ISSUE THREAD

**Issue by leoluk** [asymmetric-research/solana_exporter#6]

**Comment by mcamou** [comment]
`solana_leader_slots_total{status="skipped"}` does not match the output of `getBlockProduction`. As an example, pointing to the PythNet RPC node I get 3 total skipped slots for the current epoch (345). If I do `sum by(nodekey)(delta(solana_leader_slots_total{status="skipped"}[4h]))`, at 2024-05-27 14:00:00 UTC I get that node `8hVkKECTe5YdY7tzSkxB6Mx5cWuXxngjiFmqnCqR4ppU` had 137 skipped slots.

**Comment by SEJeff** [comment]
Fixed in #12 courtesy of @mcamou
